import { Icons } from "../icons";

export const STAGES_DATA = [
    {
        id: 1,
        label: "Idea",
        icon: Icons.stages.idea,
        color: "#F5A843",
        mission: "Prove the problem is real before building anything",
        briefing: `Before you build anything — before you name it, brand it, or spend a dollar on it — you need to know one thing with certainty: does this problem actually exist, and will someone pay you to solve it?\n\nMost founders skip this. They fall in love with their solution and build it hoping customers will appear. Forge won't let you make that mistake.\n\nThis stage is about getting out of the building and into real conversations. Not surveys. Not hypotheticals. Real people telling you real things about a real problem they actually have.`,
        innerCircle: [
            "Rob Fitzpatrick — The Mom Test",
            "Eric Ries — The Lean Startup",
            "Peter Thiel — Zero to One",
            "Geoffrey Moore — Crossing the Chasm",
            "W. Chan Kim — Blue Ocean Strategy",
        ],
        frameworks: [
            "The Mom Test interview method",
            "Problem-Solution Fit",
            "Jobs To Be Done",
            "The Lean Startup Loop",
            "Blue Ocean Strategy Canvas",
        ],
        milestones: [
            { id: "idea_1", label: "Defined the specific problem in one clear sentence" },
            { id: "idea_2", label: "Identified target customer with real specificity — not 'everyone'" },
            { id: "idea_3", label: "Conducted at least 5 real customer conversations using Mom Test principles" },
            { id: "idea_4", label: "Found evidence people currently pay for an imperfect alternative" },
            { id: "idea_5", label: "Got willingness-to-pay signals from at least 3 people" },
        ],
        forgeOpener: (name: string) => `${name} — welcome to **Stage 1**. This is where most founders either win or lose before they even know it.\n\nThe mission is simple and non-negotiable: **prove the problem is real** before you build the solution. Rob Fitzpatrick says most founders ask the wrong questions and get polite lies in return. We're going to do this right.\n\nFirst question — describe the **problem** you're solving in one sentence. Not your solution. The problem. What painful thing exists in someone's life that your business fixes?`,
    },
    {
        id: 2,
        label: "Plan",
        icon: Icons.stages.plan,
        color: "#63B3ED",
        mission: "Build a coherent business model before spending serious money",
        briefing: `You've validated the problem. Now we build the model — the system that turns solving that problem into a sustainable business.\n\nA business plan isn't a 40-page document. It's a single coherent answer to: who are my customers, what do I give them, how do I reach them, how do I make money, and what makes me hard to copy?\n\nGet this right and every decision downstream gets easier. Get it wrong and you'll be rebuilding it later — with real money already spent.`,
        innerCircle: [
            "Jim Collins — Good to Great",
            "Jim Collins & Jerry Porras — Built to Last",
            "Michael Gerber — The E-Myth Revisited",
            "Roger Martin — Playing to Win",
            "Gabriel Weinberg — Traction",
        ],
        frameworks: [
            "Business Model Canvas",
            "The Hedgehog Concept",
            "Playing to Win Strategy Choice Cascade",
            "Traction Channel Testing",
            "The E-Myth Technician-Manager-Entrepreneur Framework",
        ],
        milestones: [
            { id: "plan_1", label: "Completed a one-page Business Model Canvas" },
            { id: "plan_2", label: "Defined the revenue model — exactly how money is made" },
            { id: "plan_3", label: "Mapped the top 3 competitors and identified the real gap" },
            { id: "plan_4", label: "Written a clear value proposition in one sentence" },
            { id: "plan_5", label: "Identified the first viable customer acquisition channel" },
        ],
        forgeOpener: (name: string) => `${name} — **Stage 2**. The validation work is done. Now we build the model.\n\nThis is where I need you to think like a **strategist**, not just a founder. Jim Collins found that the companies that went from good to great all shared something — they identified what he called their **Hedgehog Concept**: the one thing they could be the best in the world at, that also made economic sense, and that they were genuinely passionate about.\n\nGerber calls the trap the **fatal assumption**: most founders are technically skilled at what they do but don't know how to run a business that does it at scale.\n\nLet's start with revenue. Exactly how does this business make money — and how much per transaction or per month?`,
    },
    {
        id: 3,
        label: "Legal",
        icon: Icons.stages.legal,
        color: "#9F7AEA",
        mission: "Protect the business and the founder with the right structure",
        briefing: `Legal work isn't glamorous. But nothing kills a promising business faster than getting the structure wrong at the start — or ignoring it entirely.\n\nYou don't need a lawyer for everything. You do need to understand what you're setting up, why, and what it protects you from. Forge will walk you through the decisions clearly.\n\nOne rule: for anything complex or high-stakes, Forge will always tell you to talk to a real attorney or CPA. That's not a cop-out — it's the right call.`,
        innerCircle: [
            "Tom Wheelwright — Tax-Free Wealth",
            "Nolo Press — Legal Guide for Starting & Running a Small Business",
            "The Outsiders — William Thorndike (capital structure thinking)",
            "Michael Gerber — The E-Myth (structure builds independence)",
        ],
        frameworks: [
            "Entity Structure Decision Tree (Sole Prop → LLC → S-Corp → C-Corp)",
            "IP Protection Basics",
            "Co-Founder Agreement Framework",
            "Business Banking Separation",
            "Tax Entity Optimization",
        ],
        milestones: [
            { id: "legal_1", label: "Chose and registered a business entity type (LLC, Sole Prop, etc.)" },
            { id: "legal_2", label: "Obtained an EIN from the IRS" },
            { id: "legal_3", label: "Opened a dedicated business bank account" },
            { id: "legal_4", label: "Understood basic IP protection for the business concept" },
            { id: "legal_5", label: "Identified any licenses or permits required for the industry" },
        ],
        forgeOpener: (name: string) => `${name} — **Stage 3**. We're making this business real and legal.\n\nI'll be direct: most founders put this off because it feels bureaucratic. That's a mistake. The structure you choose now determines how you're **taxed**, how **protected** you are personally, and how attractive you are to future investors or acquirers.\n\nTom Wheelwright makes a point that changes how people think about this: 99.5% of the US tax code exists to **reduce** your taxes, not raise them. The complexity was written to reward business owners and investors who understand it.\n\nForge teaches concepts and vocabulary here — for anything specific to your situation, you'll want a real attorney or CPA. But let's make sure you understand what you're deciding.\n\nFirst: have you already chosen a business entity type, or are we starting from scratch?`,
    },
    {
        id: 4,
        label: "Finance",
        icon: Icons.stages.finance,
        color: "#48BB78",
        mission: "Build the financial foundation that makes every decision clearer",
        briefing: `Money is the language of business. And most first-time founders don't speak it fluently — not because they're not smart, but because nobody taught them.\n\nThis stage changes that. By the end, you'll know your numbers the way a seasoned operator does. Your runway, your break-even, your unit economics, your tax structure.\n\nMichalowicz's Profit First framework is the starting point: take profit first, then operate on what's left. It sounds backwards. It works. But that's just the beginning of what Stage 4 builds.`,
        innerCircle: [
            "Mike Michalowicz — Profit First",
            "Karen Berman & Joe Knight — Financial Intelligence",
            "Alex Hormozi — $100M Offers (the revenue side)",
            "Jack Stack — The Great Game of Business",
            "Tom Wheelwright — Tax-Free Wealth",
        ],
        frameworks: [
            "Profit First Account Architecture",
            "The Three Financial Statements",
            "The Value Equation (Hormozi)",
            "Unit Economics (CAC, LTV, Gross Margin)",
            "Target Allocation Percentages (TAPs)",
            "The Critical Number (Stack)",
        ],
        milestones: [
            { id: "finance_1", label: "Mapped all startup costs with realistic estimates" },
            { id: "finance_2", label: "Built a 12-month financial projection (revenue and expenses)" },
            { id: "finance_3", label: "Set a pricing model with clear rationale based on value delivered" },
            { id: "finance_4", label: "Implemented a basic Profit First account structure" },
            { id: "finance_5", label: "Knows runway to the day and break-even point" },
        ],
        forgeOpener: (name: string) => `${name} — **Stage 4**. This is where I pay the most attention.\n\nMore businesses fail from **financial mismanagement** than from bad ideas. Not because founders are careless — because nobody gave them a real system.\n\nMichalowicz's **Profit First** flips the conventional model: instead of Revenue − Expenses = Profit, you run Revenue − Profit = Expenses. You take profit first, then operate on what's left. It creates discipline automatically.\n\nBut Stage 4 is bigger than cash management. We're building your complete financial intelligence — how to read your statements, how to price for value not cost, how to understand your taxes before they surprise you, and how to build a business where the numbers tell you what to do next.\n\nBefore we build your projection — tell me your current total budget and what you've spent so far.`,
    },
    {
        id: 5,
        label: "Launch",
        icon: Icons.stages.launch,
        color: "#E8622A",
        mission: "Get the first paying customers and a repeatable way to find more",
        briefing: `This is the stage most founders are most afraid of — and the one that matters most.\n\nLaunch doesn't mean a press release and a party. It means the first real transaction. Someone giving you real money for real value. Everything before this was preparation. This is the beginning.\n\nHormozi's core insight: if you don't have enough leads, it's because you're not advertising enough, with enough skill, or with enough volume. Lead generation is a skill, not luck. And every sale is a negotiation — whether you know it or not.`,
        innerCircle: [
            "Alex Hormozi — $100M Leads",
            "Chris Voss — Never Split the Difference",
            "Harry Beckwith — Selling the Invisible",
            "Zig Ziglar — Secrets of Closing the Sale",
            "Seth Godin — Permission Marketing",
        ],
        frameworks: [
            "The Core Four (Hormozi)",
            "LTGP:CAC Ratio",
            "The Value Equation",
            "Never Split the Difference Negotiation Method",
            "Permission Marketing — Anticipated, Personal, Relevant",
            "The Grand Slam Offer (from Stage 4)",
        ],
        milestones: [
            { id: "launch_1", label: "Defined the launch strategy — beachhead segment identified" },
            { id: "launch_2", label: "Built the minimum viable customer-facing presence" },
            { id: "launch_3", label: "Acquired the first paying customer" },
            { id: "launch_4", label: "Collected real customer feedback post-purchase" },
            { id: "launch_5", label: "Established a repeatable process for acquiring the next customer" },
        ],
        forgeOpener: (name: string) => `${name} — **Stage 5**. This is the one that separates people who want to start a business from people who actually do.\n\nEverything before this was preparation. This stage ends with **real money from a real customer**. Not a pre-sign-up. Not a maybe. A transaction.\n\nHormozi says if you don't have enough leads, there are only three reasons: not advertising enough, not with enough skill, or not with enough volume. Lead generation is a **learnable skill**. Every person you can contact right now is a potential lead.\n\nThe first move is always warm outreach. Let's start there. Who are the people in your life — friends, family, former colleagues, anyone — who either have the problem you're solving or know people who do?`,
    },
    {
        id: 6,
        label: "Grow",
        icon: Icons.stages.grow,
        color: "#F5A843",
        mission: "Scale what's working without breaking what made it work",
        briefing: `You've built something real. Now the challenge changes — from finding customers to building systems, from surviving to scaling, from founder to operator.\n\nGrowth breaks businesses that aren't ready for it. Zook and Allen at Bain found that 85% of growth failures are caused by internal factors, not external ones. The companies that scale successfully are the ones that preserve what they call the founder's mentality — insurgent mission, front-line obsession, owner's mindset — as they grow.\n\nForge stays with you here permanently. This stage doesn't end. It evolves.`,
        innerCircle: [
            "Chris Zook — The Founder's Mentality",
            "Patrick Lencioni — The Five Dysfunctions of a Team",
            "Andy Grove — Only the Paranoid Survive",
            "Sam Walton — Made in America",
            "Jim Collins — Good to Great",
        ],
        frameworks: [
            "The Founder's Mentality (Insurgent Mission + Front-Line Obsession + Owner's Mindset)",
            "The Five Dysfunctions Pyramid",
            "Strategic Inflection Points (Grove)",
            "The Flywheel (Collins)",
            "The Experience Economy Progression",
        ],
        milestones: [
            { id: "grow_1", label: "Identified the primary growth lever — acquisition, retention, or referral" },
            { id: "grow_2", label: "Documented core processes so the business doesn't depend solely on the founder" },
            { id: "grow_3", label: "Hit a consistent monthly revenue target for 3 consecutive months" },
            { id: "grow_4", label: "Made the first hire or contractor decision deliberately" },
            { id: "grow_5", label: "Built a simple dashboard tracking the 3 metrics that actually matter" },
        ],
        forgeOpener: (name: string) => `${name} — **Stage 6**. You've built something real. Take a moment with that.\n\nNow the game changes.\n\nZook and Allen found that the companies that sustain growth at scale share one trait: they preserve the **founder's mentality** — the insurgent energy, the front-line obsession, the owner's mindset — that made the first version of the business work. Most companies lose it as they grow. The ones that keep it become the best businesses in the world.\n\nCollins calls the momentum you've been building the **Flywheel**: you've been pushing it with effort. Now we build the systems that keep it spinning and accelerate it.\n\nWhat's your biggest constraint right now — more customers, more capacity, or more people?`,
    },
] as const;
