begin;

-- ─── New tags ─────────────────────────────────────────────────────────────────
insert into public.academy_tags (slug, name)
values
    ('cash-flow',             'Cash Flow'),
    ('legal-structure',       'Legal Structure'),
    ('competitive-advantage', 'Competitive Advantage'),
    ('lead-generation',       'Lead Generation'),
    ('traction',              'Traction'),
    ('burnout',               'Burnout'),
    ('visibility',            'Visibility'),
    ('ip-protection',         'IP Protection'),
    ('fundraising',           'Fundraising'),
    ('sales-discovery',       'Sales Discovery')
on conflict (slug) do update
set name = excluded.name;

-- ─── New content ──────────────────────────────────────────────────────────────
with categories as (
    select id, slug from public.academy_categories
),
upserted_content as (
    insert into public.academy_content (
        slug, title, short_description, description,
        content_type, category_id, source_type, stage_ids,
        difficulty_label, estimated_minutes,
        why_this_matters, what_to_watch_for, learning_goal,
        who_this_is_for, when_this_matters, common_mistake,
        starter_prompt, forge_context,
        video_url, youtube_video_id,
        featured, priority, status, published_at
    )
    values

    -- ── Featured Topics ────────────────────────────────────────────────────────

    (
        'llc-separation-maintenance',
        'Your LLC Is Only as Strong as the Separation You Maintain',
        'The protection exists on paper. Whether it holds up is a different question.',
        'Forming an LLC creates a legal boundary between personal and business liability — but only if that boundary is consistently maintained. Courts pierce the corporate veil when founders commingle funds, ignore formalities, or treat the entity as a personal wallet. This topic makes that risk visible before it becomes expensive.',
        'topic',
        (select id from categories where slug = 'legal'),
        'foundry_original',
        array[3],
        'Core',
        15,
        'Forming an LLC and then running your personal and business finances together is one of the most common and expensive founder mistakes. Courts call it piercing the corporate veil.',
        'Watch for founders who filed the LLC paperwork and then immediately went back to running personal and business expenses through the same account.',
        'Understand what actually maintains LLC protection and what quietly destroys it over time.',
        'Early-stage founders who have formed an entity or are about to and want real protection, not symbolic paperwork.',
        'As soon as you have an LLC and any real revenue, expenses, customers, or contracts running through the business.',
        'Assuming the protection is automatic once the paperwork is filed.',
        'Teach me what actually maintains LLC protection in practice. I want to understand what founders do that quietly destroys it.',
        'Keep this grounded in real operational behavior. Show what veil-piercing looks like in real small business situations.',
        null, null, true, 32, 'published', now()
    ),
    (
        'runway-is-a-deadline',
        'The Number That Tells You How Long You Have',
        'Runway is not a financial concept. It is a deadline.',
        'Runway is the single most important number for a pre-profitable founder. It tells you how long you have to reach a milestone before the business ends. Founders who know their exact number make better decisions. Founders who have a vague sense of it make expensive ones with a false sense of time.',
        'topic',
        (select id from categories where slug = 'finance'),
        'foundry_original',
        array[4],
        'Core',
        14,
        'Every decision a pre-profitable founder makes should be evaluated against its effect on runway first. Founders who do not know their exact number make expensive decisions confidently.',
        'Watch for founders who know their bank balance but not their monthly burn rate, or who calculate runway without accounting for upcoming large payments.',
        'Build the habit of knowing your exact runway at all times and making decisions through that lens.',
        'Pre-revenue or pre-profitable founders who are operating with a finite cash balance and no clear sense of how long it lasts.',
        'Right now, and every time you are considering a significant spend, hire, or pivot that changes your burn rate.',
        'Calculating runway based on current cash without accounting for upcoming large expenses.',
        'Teach me how to calculate and manage runway as a first-time founder. I want to understand it as a decision tool, not just a finance metric.',
        'Keep this operationally focused. The founder should leave knowing their number and knowing how to use it.',
        null, null, true, 34, 'published', now()
    ),
    (
        'profitable-on-paper-broke-in-reality',
        'Profitable on Paper, Broke in Reality',
        'Profit and cash are not the same number. Confusing them is fatal.',
        'Accounting profit and cash in the bank are two different things. A business can show a positive P&L every month and still run out of money because of timing differences between when revenue is earned and when cash arrives. This topic makes that gap visible and explains why it destroys businesses that should have survived.',
        'topic',
        (select id from categories where slug = 'finance'),
        'foundry_original',
        array[4],
        'Core',
        16,
        'A business can show accounting profit every month and still run out of money. Understanding cash flow versus profit is the difference between a founder who survives growth and one who gets destroyed by it.',
        'Watch for founders who check the P&L and assume the bank account reflects the same reality, especially during periods of fast revenue growth.',
        'Understand the difference between accounting profit and cash flow and why both must be managed separately.',
        'Founders with early revenue who are starting to see growth but have not yet learned that growing revenue can cause cash crises.',
        'As soon as revenue starts growing, invoicing is involved, or payment timing creates gaps between earning and receiving.',
        'Looking at the P&L and assuming the bank account reflects the same reality.',
        'Explain the difference between profit and cash flow like a founder coach, not an accountant. Show me where this kills businesses.',
        'Use real-world examples where profitable businesses ran out of money. Make the distinction visceral, not theoretical.',
        null, null, true, 36, 'published', now()
    ),
    (
        'sales-conversation-discovery-process',
        'The Sales Conversation Is a Discovery Process',
        'The founder who pitches first learns nothing. The one who listens first closes more.',
        'Most founders treat the sales conversation as a moment to present their product. The founders who close consistently treat it as an investigation. They are trying to understand the customer''s situation, the real cost of the problem, and whether their offer is actually the right fit. Presenting before discovering produces bad data and bad close rates.',
        'topic',
        (select id from categories where slug = 'sales'),
        'foundry_original',
        array[5],
        'Core',
        15,
        'Most founders treat the sales conversation as a presentation of their product. The founders who close treat it as an investigation of the customer''s situation.',
        'Watch for founders who lead with features, pricing, or demos before they have established what the customer''s actual situation is.',
        'Develop a discovery-first sales posture that produces better customer understanding and better close rates.',
        'Founders who are actively selling and want to improve their conversations, especially those who pitch hard but close weakly.',
        'Before your next sales conversation, and especially when a pitch feels like it lands but the deal still does not close.',
        'Presenting before understanding what the customer actually needs and whether the product fits.',
        'Teach me how to run a sales conversation that discovers before it presents. I want to close more by talking less.',
        'Focus on the structure of discovery: what to ask, how to listen, and when to present. Keep it practically usable.',
        null, null, true, 38, 'published', now()
    ),
    (
        'unit-economics-decide-whether-growth-helps-or-hurts',
        'Unit Economics Decide Whether Growth Helps or Hurts',
        'Scale amplifies whatever is already true at the unit level. Fix the unit first.',
        'A business with broken unit economics gets worse as it grows. Every new customer accelerates the loss. The unit is the building block — one customer, one transaction, one subscription. If that unit does not work, adding more units makes things worse faster. This topic teaches founders to see and fix the unit before they chase scale.',
        'topic',
        (select id from categories where slug = 'business-fundamentals'),
        'foundry_original',
        array[2,4],
        'Core',
        16,
        'A business with broken unit economics gets worse as it grows. Every new customer accelerates the loss. Understanding the economics of one sale is the prerequisite to scaling anything.',
        'Watch for founders who celebrate revenue growth while unit contribution margins are negative or unknown.',
        'Build the ability to evaluate the economics of a single customer or transaction before scaling.',
        'Founders with early customers or revenue who are starting to think about growth without having tested whether the unit works.',
        'Before you spend on paid acquisition, hire a sales team, or make growth plans that assume the unit is already healthy.',
        'Confusing revenue growth with business health.',
        'Teach me how to think about unit economics at the level of one customer or transaction. I want to know if the unit actually works before I try to scale it.',
        'Keep it practical and decision-oriented. The founder should be able to evaluate their unit economics after this conversation.',
        null, null, true, 40, 'published', now()
    ),
    (
        'the-contract-you-did-not-sign',
        'The Contract You Did Not Sign Is the One That Gets You',
        'Verbal agreements feel fine until they are not.',
        'The contract protects both parties from the ambiguity that good relationships hide. Founders who skip written agreements with early customers, contractors, and partners create invisible risk that only becomes visible when something goes wrong, the relationship ends, or money becomes serious. This topic makes the cost of informality concrete before it arrives.',
        'topic',
        (select id from categories where slug = 'legal'),
        'foundry_original',
        array[3,5],
        'Applied',
        14,
        'The contract protects both parties, not just you. Founders who skip contracts with early customers, early contractors, and early partners create expensive ambiguity that becomes very clear when something goes wrong.',
        'Watch for founders who assume a good relationship removes the need for written terms, especially with people they trust.',
        'Build the discipline of written agreements before relationship complexity makes them awkward to introduce.',
        'Founders working with early customers on custom terms, bringing on contractors, or entering informal partnerships.',
        'Before any arrangement involving money, deliverables, IP, equity, or ongoing obligations with another person or company.',
        'Assuming a handshake deal is fine because the relationship feels solid.',
        'Teach me why verbal agreements create hidden risk and what kinds of written agreements a founder actually needs early.',
        'Keep this practical and non-paranoid. The founder should feel equipped, not anxious.',
        null, null, true, 42, 'published', now()
    ),
    (
        'competitive-advantage-is-what-they-cannot-copy',
        'Competitive Advantage Is What They Cannot Copy, Not What You Do Well',
        'Being good at something is not a moat. Being hard to replicate is.',
        'Most founders describe their competitive advantage in terms of execution quality, team experience, or customer service. These are real strengths but they are not competitive advantages in a strategic sense. A true competitive advantage is a structural reason why competitors cannot easily replicate what you do. This topic sharpens that distinction.',
        'topic',
        (select id from categories where slug = 'business-fundamentals'),
        'foundry_original',
        array[2],
        'Applied',
        15,
        'Most founders describe their competitive advantage in terms of what they do rather than why competitors cannot do it. Those are different questions with different answers.',
        'Watch for advantages that a well-funded competitor could replicate in six to twelve months with enough effort.',
        'Develop a more rigorous definition of competitive advantage that goes beyond execution quality.',
        'Founders who have early traction and are starting to think seriously about positioning, defensibility, and long-term strategy.',
        'When an investor asks about your moat, when a competitor appears, or when you are building strategy around claims that feel thin under pressure.',
        'Calling customer service or team quality a competitive advantage.',
        'Help me think more rigorously about competitive advantage. I want to know whether mine is real or whether it is just something I do well right now.',
        'Push the founder to test whether each claimed advantage is structural or just a current execution lead.',
        null, null, true, 44, 'published', now()
    ),
    (
        'price-is-the-most-powerful-lever',
        'Price Is the Most Powerful Lever You Are Probably Pulling Wrong',
        'Most founders underprice. The reasons are almost always psychological, not strategic.',
        'Pricing is where founder psychology, market positioning, and business economics collide. Most first-time founders set prices based on what feels safe rather than what the value supports. This compounds quietly: lower margins, lower perceived value, worse customers, harder decisions. This topic makes the full effect of pricing visible before the damage is done.',
        'topic',
        (select id from categories where slug = 'finance'),
        'foundry_original',
        array[2,4,5],
        'Applied',
        16,
        'Pricing affects who you attract, what margins you operate on, how seriously the market takes you, and whether the business is viable. Getting it wrong compounds quietly.',
        'Watch for founders who set price before testing what value the market actually assigns to their offer.',
        'Build a more strategic relationship with pricing so it serves business health rather than founder comfort.',
        'Founders pricing an offer, a service, a pilot, or a product who have not yet tested whether the current price is strategic or defensive.',
        'Before you lock in a price, before you raise it, and whenever you find yourself discounting to close deals.',
        'Setting price based on what feels safe rather than what the value actually supports.',
        'Help me think about pricing as a strategic decision rather than a comfort choice. I want to understand what my price is communicating.',
        'Challenge the psychological component early. Then move toward the structural impact of pricing on customer quality, margins, and positioning.',
        null, null, true, 46, 'published', now()
    ),
    (
        'lead-generation-before-you-have-a-brand',
        'Lead Generation Before You Have a Brand',
        'You cannot wait for inbound. The first customers require founder effort.',
        'Every successful company got its first customers through direct founder-to-customer outreach. Inbound, referrals, and organic channels come later — after the founder has already built a base through personal selling. This topic teaches founders how to generate leads when they have no brand, no reputation, and no marketing budget.',
        'topic',
        (select id from categories where slug = 'sales'),
        'foundry_original',
        array[5],
        'Applied',
        15,
        'Every successful company got its first customers through direct founder-to-customer outreach. Understanding how to generate leads before you have a brand is the skill that determines whether the business gets off the ground.',
        'Watch for founders who are waiting for a channel, a website, or a content strategy to generate leads instead of doing the uncomfortable direct work.',
        'Build the founder''s ability to generate conversations and leads through direct outreach before inbound channels exist.',
        'Early-stage founders with a defined offer who need real customer conversations but have no established lead source.',
        'Before you have paying customers, when the pipeline is empty, or when every lead currently comes from your personal network.',
        'Building a product and expecting marketing to replace the founder sales conversations that actually need to happen.',
        'Teach me how to generate leads as a first-time founder before I have any brand recognition or inbound momentum.',
        'Keep this direct and tactical. The founder should leave with specific outreach approaches they can use this week.',
        null, null, true, 48, 'published', now()
    ),
    (
        'traction-is-evidence-not-activity',
        'Traction Is Evidence, Not Activity',
        'Busy is not the same as moving forward.',
        'Founders confuse activity with traction constantly. Being busy, getting meetings, having warm conversations, and watching website traffic tick up all feel like progress. Real traction is a different standard: evidence that the market wants what you are selling, expressed through behavior, not sentiment.',
        'topic',
        (select id from categories where slug = 'business-fundamentals'),
        'foundry_original',
        array[1,2,5],
        'Strategic',
        14,
        'Founders confuse activity with traction constantly. Real traction is evidence the market wants what you are selling. Everything else is motion that feels like progress.',
        'Watch for founders describing activity metrics — meetings, impressions, signups, warm responses — as though they are traction signals.',
        'Build a more rigorous definition of traction that the founder can apply to their own business without self-deception.',
        'Founders in early stages who are working hard and want to know if the work is actually moving the needle.',
        'Whenever you are presenting "progress" to anyone, including yourself, and need to know whether it is real.',
        'Treating website visits, social follows, and warm conversations as traction signals.',
        'Help me understand what real traction looks like versus what just looks like progress. I want a standard I can actually use.',
        'Challenge soft traction claims directly. Push the founder toward evidence of behavior, not expressed interest.',
        null, null, true, 50, 'published', now()
    ),

    -- ── Videos ────────────────────────────────────────────────────────────────

    (
        'business-structure-tax-liability-decision',
        'Why Your Business Structure Is a Tax and Liability Decision',
        'The entity you choose determines how much you keep and how much you risk.',
        'Most founders pick an LLC because someone told them to. Understanding why structure matters — and what it actually does and does not protect — changes how you run the business operationally, not just on paper.',
        'video',
        (select id from categories where slug = 'legal'),
        'foundry_original',
        array[3],
        'Practical',
        14,
        'Most founders pick an LLC because everyone told them to. Understanding why the structure matters — and what it actually does and does not protect — changes how you run the business.',
        'Watch for where entity choice connects to operating discipline — the protection is ongoing, not one-time.',
        'Understand why entity structure is both a tax decision and a liability decision that requires ongoing maintenance.',
        'Founders who have or are about to form a legal entity and want to understand what they actually signed up for.',
        'When you are forming an entity, hiring, bringing on partners, or signing your first real contracts.',
        'Treating entity formation as a one-time paperwork task rather than an ongoing operational discipline.',
        'Walk me through why business structure is a real ongoing decision — not just paperwork. Show me what founders miss.',
        'Connect entity choice to operational behavior. The founder should understand what maintaining the structure actually requires.',
        null, null, false, 218, 'published', now()
    ),
    (
        'how-to-read-a-pl-without-accounting-degree',
        'How to Read a P&L Without an Accounting Degree',
        'The profit and loss statement is not a mystery. It is a story about the business.',
        'Every investor, bank, and serious business partner will expect you to understand your own financial statements. Founders who cannot read a P&L make worse decisions and signal to others that they do not fully own their business. This video makes the statement readable without accounting background.',
        'video',
        (select id from categories where slug = 'finance'),
        'foundry_original',
        array[4],
        'Practical',
        16,
        'Every investor, every bank, and every serious business partner will expect you to understand your own financial statements. Founders who cannot read a P&L make worse decisions and look less credible to people they need.',
        'Watch for the connection between P&L line items and the real business decisions they reflect.',
        'Build enough financial literacy to read a P&L confidently and ask the right questions from it.',
        'Founders who rely on their accountant to interpret financial statements and want to close that gap.',
        'Before your first investor conversation, when you are reviewing monthly financials, or when you realize you cannot explain your own numbers.',
        'Leaving financial literacy to the accountant and only checking in at tax time.',
        'Teach me how to read a P&L in practical terms. I want to understand what each line actually tells me about the business.',
        'Keep it applied and non-technical. The founder should leave able to read their own statement and know what questions to ask.',
        null, null, false, 220, 'published', now()
    ),
    (
        'first-sales-conversation-that-moves',
        'How to Have a First Sales Conversation That Actually Moves',
        'The first conversation is not a pitch. It is a structured exploration.',
        'Most first sales conversations fail because the founder pitches instead of discovers. Understanding the structure of a productive first conversation — who speaks when, what questions matter, when to present — changes close rates immediately and teaches founders more about their customer along the way.',
        'video',
        (select id from categories where slug = 'sales'),
        'foundry_original',
        array[5],
        'Practical',
        15,
        'Most first sales conversations fail because the founder pitches instead of discovers. Understanding the structure of a productive first conversation changes close rates immediately.',
        'Watch for the difference between a discovery structure and a pitch structure — they produce different outcomes from the same conversation.',
        'Develop a practical structure for the first sales conversation that produces customer understanding and a clear next step.',
        'Founders who are having first conversations with potential customers and want to close more of them.',
        'Before your next sales conversation, especially if your close rate is low and you cannot identify why.',
        'Showing up with a demo before understanding whether the problem actually exists for this specific person.',
        'Walk me through the structure of a first sales conversation that actually produces a result. I want to stop pitching and start discovering.',
        'Keep this applicable immediately. The founder should be able to run this structure in their next call.',
        null, null, false, 222, 'published', now()
    ),
    (
        'how-to-find-your-beachhead-market',
        'How to Find Your Beachhead Market',
        'Owning one small market completely is the path to a large market eventually.',
        'Crossing the Chasm research shows that mainstream markets are won by companies who dominated a specific beachhead first. Trying to serve everyone from day one is how you end up serving nobody particularly well. This video teaches founders how to identify and commit to a beachhead before expanding.',
        'video',
        (select id from categories where slug = 'business-fundamentals'),
        'foundry_original',
        array[1,2,5],
        'Strategic',
        17,
        'Crossing the Chasm research shows that mainstream markets are won by companies who owned a specific beachhead first. Trying to serve everyone from day one is how you serve nobody well.',
        'Watch for how beachhead selection changes focus, messaging, offer design, and early customer success — not just targeting.',
        'Understand how to identify and own a specific initial market segment before attempting to expand.',
        'Founders in the market definition or early traction phase who are trying to figure out who to serve first.',
        'When you realize your customer definition is still vague, or when marketing and sales feel scattered because you are targeting everyone.',
        'Targeting the total addressable market before earning the right to expand.',
        'Help me understand how to find and commit to a beachhead market. I want to understand why narrow focus leads to broader success.',
        'Challenge any remaining "target everyone" thinking. Push the founder toward a specific, winnable first market.',
        null, null, false, 224, 'published', now()
    ),
    (
        'what-best-founders-do-on-ordinary-tuesdays',
        'What the Best Founders Do Differently on Ordinary Tuesdays',
        'The gap between founders who build something real and those who do not is mostly visible in the unremarkable days.',
        'The habits, disciplines, and daily rhythms of successful founders are not glamorous. They are consistent. Understanding what those behaviors actually look like makes them easier to adopt before the pressure of growth removes the option to build them deliberately.',
        'video',
        (select id from categories where slug = 'winners-mindset'),
        'foundry_original',
        array[1,2,3,4,5,6],
        'Practical',
        14,
        'The habits, disciplines, and daily rhythms of successful founders are not glamorous. They are consistent. Understanding what those behaviors actually look like makes them easier to adopt.',
        'Watch for what founders protect when things get busy — the non-negotiable disciplines that do not disappear under pressure.',
        'Build a more honest picture of what effective founder behavior looks like on ordinary days, not peak moments.',
        'Founders at any stage who want to build better operational habits and rhythms before circumstances force it.',
        'When you are wondering why some weeks feel productive and others feel scattered despite equal effort.',
        'Waiting for motivation to show up before doing the work that creates motivation.',
        'Show me what the most effective founders actually do on ordinary days. I want the honest version, not the highlight reel.',
        'Keep this grounded in real behavioral specifics. Avoid motivational framing — this is about discipline and structure.',
        null, null, false, 226, 'published', now()
    ),
    (
        'when-to-raise-money',
        'When to Raise Money and When That Would Be a Mistake',
        'Raising capital is not validation. It is leverage. And leverage amplifies everything, including the mistakes.',
        'Many founders raise money before they understand what they are raising it for or whether they actually need it. Capital without product-market fit accelerates failure. Capital with it accelerates success. The decision to raise is one of the highest-stakes calls a founder makes and it is rarely taught clearly.',
        'video',
        (select id from categories where slug = 'finance'),
        'foundry_original',
        array[4,5,6],
        'Strategic',
        18,
        'Many founders raise money before they understand what they are raising it for or whether they actually need it. Capital without product-market fit accelerates failure.',
        'Watch for where fundraising is being treated as a milestone instead of a strategic tool — and what that signals about the business underneath.',
        'Build a clearer framework for when raising capital is the right move and when it would amplify existing problems.',
        'Founders approaching or considering their first or second funding round who want to make the decision with more clarity.',
        'Before you start a fundraising process, when investors start expressing interest, or when the team starts using "we should raise" as a strategy.',
        'Treating a funding round as the milestone instead of the tool.',
        'Help me think clearly about whether and when to raise money. I want a framework, not a fundraising playbook.',
        'Challenge any romanticized view of funding. Push the founder to understand what capital amplifies in their specific situation.',
        null, null, false, 228, 'published', now()
    ),

    -- ── Resources ─────────────────────────────────────────────────────────────

    (
        'founders-legal-checklist',
        'The Founder''s Legal Checklist — What to Have Before You Need It',
        'A practical reference for the documents that protect you before the situation that requires them.',
        'Legal protection is only useful if it exists before the dispute. This reference tells you exactly what documents every early-stage founder should have in place, why each one matters, and at what stage they become non-optional.',
        'resource',
        (select id from categories where slug = 'legal'),
        'foundry_original',
        array[3],
        'Core',
        10,
        'Legal protection is only useful if it exists before the dispute. This checklist tells you exactly what documents every early-stage founder should have in place and why each one matters.',
        'Watch for gaps between what you currently have and what would protect you if a customer, contractor, or partner dispute emerged today.',
        'Give the founder a clear reference for early legal infrastructure so nothing critical is missing when it matters.',
        'Founders who are formalizing their business, working with first customers, or bringing on any contractors or partners.',
        'Before your first significant contract, before you hire or contract anyone, and before any equity or partnership arrangement.',
        'Treating legal infrastructure as something to figure out after the first problem arrives.',
        'Walk me through the legal documents every early-stage founder should have and help me see where I have gaps.',
        'Make this feel like a practical audit, not a legal scare tactic. The founder should leave with a specific action list.',
        null, null, false, 316, 'published', now()
    ),
    (
        'financial-metrics-that-tell-the-truth',
        'The Financial Metrics That Actually Tell You How the Business Is Doing',
        'Most founders track the wrong numbers. These are the ones that tell the truth.',
        'Revenue is a vanity metric without context. Understanding the metrics that actually indicate business health — gross margin, CAC, LTV, burn rate, runway — changes what you pay attention to and when you get worried. This resource gives founders a clear view of which numbers matter and what each one is telling them.',
        'resource',
        (select id from categories where slug = 'finance'),
        'foundry_original',
        array[4,6],
        'Core',
        11,
        'Revenue is a vanity metric without context. Understanding the metrics that actually indicate business health — gross margin, CAC, LTV, burn rate, runway — changes what you pay attention to and when you get worried.',
        'Watch for which metrics a founder is currently tracking versus which ones would actually tell them if the business was in trouble.',
        'Give the founder a clear map of which financial metrics matter most and how to interpret each one.',
        'Founders with early revenue who want to build better financial awareness without becoming accountants.',
        'When you are reviewing monthly financials, preparing for an investor conversation, or just trying to know if the business is actually healthy.',
        'Tracking revenue growth as the primary health indicator while ignoring the metrics below it.',
        'Walk me through the financial metrics that actually tell me if the business is healthy. I want to understand what each one means.',
        'Keep this practical and connected to real founder decisions. The founder should leave knowing which metrics to watch weekly.',
        null, null, false, 318, 'published', now()
    ),
    (
        'one-page-offer-framework',
        'The One-Page Offer Framework',
        'If you cannot describe your offer clearly in one page, the offer is not clear enough yet.',
        'A documented offer forces the clarity that verbal descriptions hide. Founders who write down exactly what they are selling, to whom, at what price, with what guarantee, and what the customer gets almost always discover that the offer was fuzzier than they thought. This resource gives a clean one-page format to do that work.',
        'resource',
        (select id from categories where slug = 'sales'),
        'foundry_original',
        array[2,5],
        'Practical',
        9,
        'A documented offer forces the clarity that verbal descriptions hide. Founders who write down exactly what they are selling, to whom, at what price, with what guarantee, almost always discover that the offer was fuzzier than they thought.',
        'Watch for where the written version of the offer reveals assumptions or gaps that the founder had been talking past.',
        'Give the founder a clean format for documenting their offer with enough specificity to reveal and fix weak points.',
        'Founders shaping, launching, or revising a service offer, product, or pricing page.',
        'Before any significant sales push, before rewriting a landing page, and before you send a proposal to a serious potential customer.',
        'Assuming the offer is clear because it makes sense internally.',
        'Help me document my offer on one page in a way that forces the clarity I might be avoiding.',
        'Guide the founder through each component of the offer document and push on any section that stays vague.',
        null, null, false, 320, 'published', now()
    ),
    (
        'business-model-canvas-working-tool',
        'The Business Model Canvas — A Working Tool, Not a Pitch Slide',
        'The canvas is most useful when it surfaces what you do not know yet.',
        'Most founders use the Business Model Canvas as a summary of decisions they have already made. Its real value is as a diagnostic tool — showing which assumptions are untested and which boxes are filled with hope rather than evidence. This resource teaches founders to use it as a live instrument rather than a finished picture.',
        'resource',
        (select id from categories where slug = 'business-fundamentals'),
        'foundry_original',
        array[2],
        'Strategic',
        10,
        'Most founders use the Business Model Canvas as a summary of decisions already made. Its real value is as a diagnostic tool — showing you which assumptions are untested and which boxes you are filling in with hope rather than evidence.',
        'Watch for where a canvas reveals untested assumptions the founder has been treating as settled.',
        'Teach founders to use the Business Model Canvas as a hypothesis-testing instrument, not a slide deck component.',
        'Founders in early planning, pivoting, or strategy refinement who want a practical framework for business model thinking.',
        'When you are stress-testing a direction, when assumptions are starting to feel thin, or when you want a structured view of the business.',
        'Completing the canvas as a validation exercise instead of a hypothesis-testing tool.',
        'Use the Business Model Canvas as a thinking tool with me. Help me identify which assumptions are still untested.',
        'Work through each section as an assumption audit. Surface what the founder is hoping is true versus what they have evidence for.',
        null, null, false, 322, 'published', now()
    ),
    (
        'how-to-protect-your-ip-before-revenue',
        'How to Protect Your IP Before You Have Revenue',
        'The time to protect what you build is before someone else tries to take it.',
        'Intellectual property protection is not just for large companies. Trademarks, copyrights, and trade secrets are tools available to early-stage founders, and the cost of using them is far lower than the cost of not having them when you need them. This resource explains the practical steps available before the business has scale.',
        'resource',
        (select id from categories where slug = 'legal'),
        'foundry_original',
        array[3],
        'Applied',
        10,
        'Intellectual property protection is not just for large companies. Trademarks, copyrights, and trade secrets are tools available to early-stage founders and the cost of using them is far lower than the cost of not having them when you need them.',
        'Watch for unprotected brand names, unwritten work-for-hire agreements with contractors, and undocumented trade secrets.',
        'Give the founder a practical map of IP protection tools available before the business has scale.',
        'Founders who are building something with real differentiation and have not yet done the basic IP housekeeping.',
        'Before you launch publicly, before you use contractors to build anything proprietary, and before you invest significantly in a brand name.',
        'Assuming IP protection is something to think about after the business gets traction.',
        'Walk me through the IP protection steps I should take as an early-stage founder before things get complicated.',
        'Focus on practical early-stage actions: trademark search and filing, copyright basics, contractor IP assignment, trade secret practices.',
        null, null, false, 324, 'published', now()
    ),
    (
        'traction-channel-map',
        'The Traction Channel Map — Finding the One That Works for You',
        'There are nineteen ways to acquire customers. You probably need to master one before spreading to three.',
        'Gabriel Weinberg''s traction framework identifies nineteen distinct customer acquisition channels. Most successful companies grew primarily through one channel at each stage. Knowing which channels exist and which ones fit your business model is a strategic decision about where to put founder energy — not a marketing calendar.',
        'resource',
        (select id from categories where slug = 'business-fundamentals'),
        'foundry_original',
        array[2,5],
        'Core',
        10,
        'Gabriel Weinberg''s traction framework identifies nineteen distinct customer acquisition channels. Most successful companies grew primarily through one channel at each stage. Knowing which channels exist and which ones fit your business model is a strategic decision, not a marketing decision.',
        'Watch for founders trying to be present on every channel instead of choosing one to master based on business model fit.',
        'Give the founder a practical map of the nineteen traction channels and how to choose which one to test first.',
        'Founders who are past the first few customers and now need a repeatable channel for growth.',
        'When manual outreach is starting to feel like a ceiling and you need a systematic approach to channel selection.',
        'Trying to be present on every channel instead of dominant on one.',
        'Walk me through the traction channels that might work for my type of business and help me figure out which one to focus on first.',
        'Use the founder''s business model to narrow the channel list. Push toward one primary channel test rather than a multi-channel plan.',
        null, null, false, 326, 'published', now()
    ),

    -- ── Winner's Mindset ──────────────────────────────────────────────────────

    (
        'comparison-trap-rigged-leaderboard',
        'The Comparison Trap Runs on a Rigged Leaderboard',
        'You are comparing your behind-the-scenes to everyone else''s highlight reel. The game is unfair by design.',
        'Comparison to other founders is one of the most reliable ways to make yourself feel behind, discouraged, and inadequate. The founders who avoid this trap are not more confident by nature — they just stopped playing a game with no honest scoreboard. This entry makes the rigged structure visible so the founder can stop letting it run quietly.',
        'mindset',
        (select id from categories where slug = 'winners-mindset'),
        'foundry_original',
        array[1,2,3,4,5,6],
        'Mindset',
        12,
        'Comparison to other founders is one of the most reliable ways to make yourself feel behind, discouraged, and inadequate. The founders who avoid this trap are not more confident — they just stopped playing a game with no honest scoreboard.',
        'Watch for how comparison shrinks the founder''s focus from their own work to other people''s visible outcomes.',
        'Help the founder see the structural dishonesty of founder comparison so it loses its power over attention and confidence.',
        'Founders at any stage who find themselves measuring their progress against what other founders appear to be doing.',
        'Whenever comparison is slowing your decisions, narrowing your perspective, or making your work feel smaller than it is.',
        'Using other founders'' visible outcomes as the measure of your own progress.',
        'Talk to me honestly about the comparison trap. I want to understand the structure of it, not just hear that I should stop comparing.',
        'Make the rigged nature of the comparison game structural and visible. Do not just encourage the founder — expose the design flaw in the game.',
        null, null, false, 122, 'published', now()
    ),
    (
        'fear-of-visibility-is-a-business-problem',
        'Fear of Visibility Is a Business Problem, Not a Personal One',
        'The founder who cannot be seen cannot sell, cannot lead, and cannot grow.',
        'Many founders avoid putting themselves forward — in pitches, marketing, networking, and public conversations — because visibility feels like exposure to judgment. But invisibility is expensive. Every avoided moment of visibility is a missed connection, customer, or opportunity. This entry makes the business cost of hiding concrete.',
        'mindset',
        (select id from categories where slug = 'winners-mindset'),
        'foundry_original',
        array[1,5,6],
        'Mindset',
        12,
        'Many founders avoid putting themselves forward — in pitches, in marketing, in networking, in public — because visibility feels like exposure to judgment. But invisibility is expensive. Every avoided moment of visibility is a missed connection, customer, or opportunity.',
        'Watch for how avoidance of visibility shows up as "I''m not ready yet," "I don''t want to seem arrogant," or "I''ll put myself out there more once it''s better."',
        'Help the founder see fear of visibility as a business constraint rather than a personal quirk — and start shrinking it.',
        'Founders who undermarket themselves, avoid public speaking or networking, or feel uncomfortable making themselves visible in their industry.',
        'When growth is stalling and the constraint is not product or market — it is the founder''s willingness to be seen.',
        'Treating discomfort with visibility as a personality trait rather than a pattern worth interrupting.',
        'Help me understand why I avoid visibility and what it is actually costing the business. I want a useful lens, not just encouragement.',
        'Name the avoidance clearly. Then connect the dots between invisibility and specific business outcomes the founder cares about.',
        null, null, false, 124, 'published', now()
    ),
    (
        'burnout-does-not-announce-itself',
        'Burnout Does Not Announce Itself',
        'By the time it is obvious, it has usually been building for months.',
        'Founder burnout destroys more companies quietly than most visible threats. Understanding the early signals — the narrowing of perspective, the loss of curiosity, the inability to recover on weekends — makes it possible to intervene before it becomes a crisis. This entry is about recognizing burnout while there is still room to respond.',
        'mindset',
        (select id from categories where slug = 'winners-mindset'),
        'foundry_original',
        array[1,2,3,4,5,6],
        'Mindset',
        13,
        'Founder burnout destroys more companies quietly than most visible threats. Understanding the early signals — the narrowing of perspective, the loss of curiosity, the inability to recover on weekends — makes it possible to intervene before it becomes a crisis.',
        'Watch for the founder''s relationship to recovery — whether rest is actually restorative or whether it has stopped working.',
        'Help the founder recognize the early pattern of burnout before it becomes a full-scale crisis that forces a harder choice.',
        'Founders who are working hard and want to know whether they are building sustainable intensity or slowly running down.',
        'When weekends no longer feel restorative, when curiosity has narrowed, or when the work that used to energize you mostly just drains you now.',
        'Treating rest as a reward for completion rather than a requirement for performance.',
        'Talk to me honestly about burnout. I want to understand the early signals and what to do when I notice them.',
        'Be clear about the real pattern — not the dramatic version. Help the founder identify what is already showing up before it becomes a label they cannot avoid.',
        null, null, false, 126, 'published', now()
    ),
    (
        'identity-shift-building-a-business-requires',
        'The Identity Shift That Building a Business Requires',
        'You cannot think like an employee and build like an owner at the same time.',
        'Most first-time founders still carry the internal identity of someone who executes tasks rather than someone who creates systems and owns outcomes. The shift from employee mindset to owner mindset is not automatic. It is a specific set of behavioral and perceptual changes that have to be made deliberately — and the earlier a founder makes them, the faster everything else moves.',
        'mindset',
        (select id from categories where slug = 'winners-mindset'),
        'foundry_original',
        array[1,2,3,4,5,6],
        'Mindset',
        13,
        'Most first-time founders still carry the internal identity of someone who executes tasks rather than someone who creates systems and owns outcomes. The shift from employee mindset to owner mindset is not automatic — it is a specific set of behavioral changes that have to be made deliberately.',
        'Watch for how employee-identity shows up as waiting for direction, seeking permission, or optimizing for individual task completion instead of whole-system outcomes.',
        'Help the founder make the internal shift from executing individual tasks to owning outcomes and building systems.',
        'First-time founders who still find themselves defaulting to task-execution mode rather than owner-design thinking.',
        'When you notice you are waiting for someone to tell you what to do next, or when you keep doing work that should be delegated.',
        'Waiting to feel like an owner rather than choosing to think and act like one.',
        'Talk to me about the identity shift from employee to owner. I want to understand the specific behavioral changes, not just the mindset label.',
        'Be specific about the behavioral differences. Help the founder see their current defaults and what the owner version of each behavior looks like.',
        null, null, false, 128, 'published', now()
    ),
    (
        'failure-is-data',
        'Failure Is Data. What You Do With It Is the Variable.',
        'The business did not fail to teach you a lesson. But the lesson is there if you look.',
        'How a founder processes failure determines whether it becomes useful or corrosive. The founders who recover fastest are not more resilient by nature — they have a more useful relationship with negative information. This entry is about building that relationship before the next failure, not after.',
        'mindset',
        (select id from categories where slug = 'winners-mindset'),
        'foundry_original',
        array[1,2,3,4,5,6],
        'Mindset',
        12,
        'How a founder processes failure determines whether it becomes useful or corrosive. The founders who recover fastest are not more resilient by nature — they have a more useful relationship with negative information.',
        'Watch for whether the founder extracts signal from failure or protects themselves from the full information by softening the interpretation.',
        'Build a more productive relationship with failure so it generates learning instead of identity damage.',
        'Founders who have experienced a meaningful setback or who want to build the capacity to process failure cleanly before the next one.',
        'After any significant failure, missed milestone, or disappointing outcome — and before the next attempt.',
        'Treating a failed experiment as evidence about your worth rather than evidence about one specific approach.',
        'Help me build a healthier relationship with failure. I want to extract the learning without letting it become an identity hit.',
        'Separate the failure from the person clearly. Then help the founder extract the specific useful signal from the specific failed thing.',
        null, null, false, 130, 'published', now()
    ),
    (
        'perfectionism-is-fear-with-better-posture',
        'Perfectionism Is Just Fear With Better Posture',
        'It sounds like high standards. It often functions as a delay mechanism.',
        'Perfectionism keeps products unlaunched, emails unsent, and conversations avoided. It protects the founder from the discomfort of external judgment by ensuring that judgment never arrives. The cost is everything that does not exist because the conditions were never quite right. This entry names the mechanism so it becomes harder to use unconsciously.',
        'mindset',
        (select id from categories where slug = 'winners-mindset'),
        'foundry_original',
        array[1,2,5],
        'Mindset',
        12,
        'Perfectionism keeps products unlaunched, emails unsent, and conversations avoided. It protects the founder from the discomfort of external judgment by ensuring that judgment never arrives. The cost is everything that does not exist because the conditions were never quite right.',
        'Watch for where perfectionism is functioning as avoidance: the thing that stays "almost ready" longest is usually the thing the founder is most afraid to test.',
        'Help the founder recognize perfectionism as a fear response rather than a quality standard so it stops working as an unconscious delay mechanism.',
        'Founders who find themselves consistently not ready to launch, send, publish, or share — despite real progress.',
        'Whenever you catch yourself making something better instead of releasing something real.',
        'Treating perfectionism as a quality standard rather than recognizing it as avoidance in disguise.',
        'Challenge my perfectionism honestly. I want to understand whether I am protecting quality or protecting myself from judgment.',
        'Name the avoidance structure clearly without being dismissive of the real desire for quality. Help the founder see the line between the two.',
        null, null, false, 132, 'published', now()
    )

    on conflict (slug) do update
    set
        title                = excluded.title,
        short_description    = excluded.short_description,
        description          = excluded.description,
        content_type         = excluded.content_type,
        category_id          = excluded.category_id,
        source_type          = excluded.source_type,
        stage_ids            = excluded.stage_ids,
        difficulty_label     = excluded.difficulty_label,
        estimated_minutes    = excluded.estimated_minutes,
        why_this_matters     = excluded.why_this_matters,
        what_to_watch_for    = excluded.what_to_watch_for,
        learning_goal        = excluded.learning_goal,
        who_this_is_for      = excluded.who_this_is_for,
        when_this_matters    = excluded.when_this_matters,
        common_mistake       = excluded.common_mistake,
        starter_prompt       = excluded.starter_prompt,
        forge_context        = excluded.forge_context,
        video_url            = excluded.video_url,
        youtube_video_id     = excluded.youtube_video_id,
        featured             = excluded.featured,
        priority             = excluded.priority,
        status               = excluded.status,
        published_at         = excluded.published_at,
        updated_at           = now()
    returning id, slug
)
insert into public.academy_content_tags (content_id, tag_id)
select c.id, t.id
from upserted_content c
join (
    values
        ('llc-separation-maintenance',                     'legal-basics'),
        ('llc-separation-maintenance',                     'legal-structure'),
        ('runway-is-a-deadline',                           'financial-control'),
        ('runway-is-a-deadline',                           'cash-flow'),
        ('profitable-on-paper-broke-in-reality',           'financial-control'),
        ('profitable-on-paper-broke-in-reality',           'cash-flow'),
        ('sales-conversation-discovery-process',           'sales-confidence'),
        ('sales-conversation-discovery-process',           'sales-discovery'),
        ('unit-economics-decide-whether-growth-helps-or-hurts', 'unit-economics'),
        ('unit-economics-decide-whether-growth-helps-or-hurts', 'growth-metrics'),
        ('the-contract-you-did-not-sign',                  'legal-basics'),
        ('the-contract-you-did-not-sign',                  'judgment'),
        ('competitive-advantage-is-what-they-cannot-copy', 'competitive-advantage'),
        ('competitive-advantage-is-what-they-cannot-copy', 'judgment'),
        ('price-is-the-most-powerful-lever',               'pricing'),
        ('price-is-the-most-powerful-lever',               'financial-control'),
        ('lead-generation-before-you-have-a-brand',        'lead-generation'),
        ('lead-generation-before-you-have-a-brand',        'sales-confidence'),
        ('traction-is-evidence-not-activity',              'traction'),
        ('traction-is-evidence-not-activity',              'growth-metrics'),
        ('business-structure-tax-liability-decision',      'legal-structure'),
        ('business-structure-tax-liability-decision',      'legal-basics'),
        ('how-to-read-a-pl-without-accounting-degree',     'financial-control'),
        ('how-to-read-a-pl-without-accounting-degree',     'cash-flow'),
        ('first-sales-conversation-that-moves',            'sales-discovery'),
        ('first-sales-conversation-that-moves',            'sales-confidence'),
        ('how-to-find-your-beachhead-market',              'positioning-clarity'),
        ('how-to-find-your-beachhead-market',              'product-market-fit'),
        ('what-best-founders-do-on-ordinary-tuesdays',     'execution'),
        ('what-best-founders-do-on-ordinary-tuesdays',     'founder-confidence'),
        ('when-to-raise-money',                            'fundraising'),
        ('when-to-raise-money',                            'financial-control'),
        ('founders-legal-checklist',                       'legal-basics'),
        ('founders-legal-checklist',                       'legal-structure'),
        ('financial-metrics-that-tell-the-truth',          'financial-control'),
        ('financial-metrics-that-tell-the-truth',          'growth-metrics'),
        ('one-page-offer-framework',                       'offer-design'),
        ('one-page-offer-framework',                       'positioning-clarity'),
        ('business-model-canvas-working-tool',             'business-model'),
        ('business-model-canvas-working-tool',             'judgment'),
        ('how-to-protect-your-ip-before-revenue',          'ip-protection'),
        ('how-to-protect-your-ip-before-revenue',          'legal-basics'),
        ('traction-channel-map',                           'traction'),
        ('traction-channel-map',                           'growth-metrics'),
        ('comparison-trap-rigged-leaderboard',             'founder-confidence'),
        ('comparison-trap-rigged-leaderboard',             'founder-identity'),
        ('fear-of-visibility-is-a-business-problem',       'visibility'),
        ('fear-of-visibility-is-a-business-problem',       'founder-confidence'),
        ('burnout-does-not-announce-itself',               'burnout'),
        ('burnout-does-not-announce-itself',               'execution'),
        ('identity-shift-building-a-business-requires',    'founder-identity'),
        ('identity-shift-building-a-business-requires',    'execution'),
        ('failure-is-data',                                'founder-confidence'),
        ('failure-is-data',                                'judgment'),
        ('perfectionism-is-fear-with-better-posture',      'founder-identity'),
        ('perfectionism-is-fear-with-better-posture',      'execution')
) as m(content_slug, tag_slug) on m.content_slug = c.slug
join public.academy_tags t on t.slug = m.tag_slug
on conflict do nothing;

-- ─── New series ───────────────────────────────────────────────────────────────

insert into public.academy_series (
    slug, title, short_description, description,
    category_id, stage_ids, difficulty_label, estimated_minutes,
    featured, priority, status, learning_goal, published_at
)
values
    (
        'understanding-your-money',
        'Understanding Your Money',
        'A five-part series that takes a founder from financially illiterate to financially literate without requiring an accounting background.',
        'Most first-time founders navigate the financial side of their business through avoidance, outsourcing, or approximation. This series builds real financial literacy from the ground up: cash flow vs. profit, runway, reading a P&L, pricing strategy, and building a price path. Each lesson builds on the one before.',
        (select id from public.academy_categories where slug = 'finance'),
        array[4],
        'Core',
        80,
        true,
        12,
        'published',
        'Build genuine financial literacy that changes how the founder makes decisions — not just how they talk about the business.',
        now()
    ),
    (
        'the-inner-game-of-building',
        'The Inner Game of Building',
        'A six-part series on the psychological patterns that quietly determine whether a founder builds something real or stalls out.',
        'The tactical work matters. This work matters underneath it. The founders who stall out usually do not lack strategy — they lack the inner operating system to execute through uncertainty, visibility, comparison, and failure. This series names that system and helps founders build it deliberately.',
        (select id from public.academy_categories where slug = 'winners-mindset'),
        array[1,2,3,4,5,6],
        'Mindset',
        73,
        true,
        14,
        'published',
        'Build the psychological foundation that allows a founder to operate clearly through uncertainty, setbacks, and pressure.',
        now()
    )
on conflict (slug) do update
set
    title              = excluded.title,
    short_description  = excluded.short_description,
    description        = excluded.description,
    category_id        = excluded.category_id,
    stage_ids          = excluded.stage_ids,
    difficulty_label   = excluded.difficulty_label,
    estimated_minutes  = excluded.estimated_minutes,
    featured           = excluded.featured,
    priority           = excluded.priority,
    status             = excluded.status,
    learning_goal      = excluded.learning_goal,
    published_at       = excluded.published_at,
    updated_at         = now();

-- ─── Series items: Understanding Your Money ───────────────────────────────────

delete from public.academy_series_items
where series_id = (select id from public.academy_series where slug = 'understanding-your-money');

insert into public.academy_series_items (series_id, content_id, position, required)
select s.id, c.id, v.position, true
from public.academy_series s
join (
    values
        ('profitable-on-paper-broke-in-reality',   1),
        ('runway-is-a-deadline',                   2),
        ('how-to-read-a-pl-without-accounting-degree', 3),
        ('price-is-the-most-powerful-lever',       4),
        ('simple-pricing-ladder',                  5)
) as v(content_slug, position) on true
join public.academy_content c on c.slug = v.content_slug
where s.slug = 'understanding-your-money';

-- ─── Series items: The Inner Game of Building ─────────────────────────────────

delete from public.academy_series_items
where series_id = (select id from public.academy_series where slug = 'the-inner-game-of-building');

insert into public.academy_series_items (series_id, content_id, position, required)
select s.id, c.id, v.position, true
from public.academy_series s
join (
    values
        ('identity-shift-building-a-business-requires', 1),
        ('fear-of-visibility-is-a-business-problem',    2),
        ('imposter-syndrome-loves-vague-standards',     3),
        ('hesitation-is-usually-self-protection',       4),
        ('burnout-does-not-announce-itself',            5),
        ('confidence-is-built-from-reps-not-mood',      6)
) as v(content_slug, position) on true
join public.academy_content c on c.slug = v.content_slug
where s.slug = 'the-inner-game-of-building';

commit;
